;; (package-initialize)
(setq inhibit-startup-screen t)
(setq make-backup-files nil)
;; (setq-default truncate-lines t)
(menu-bar-mode 0)
(tool-bar-mode 0)
;; (set-default-font "")
(setq tab-width 4)
(setq tab-stop-list '(4 8 12 16 20 24 28 32 36 40 44 48 52 56 60 64 68 72 76 80))
(setq-default c-basic-offset 4)
;; enable line highlight
;; (global-hl-line-mode 1)
;; (set-face-attribute 'highlight nil :background "#404142" :foreground 'unspecified :underline nil)
;; color-scheme
(deftheme untitled "custom-color-theme")
  (custom-theme-set-faces 'untitled
   '(default ((t (:foreground "#d5ba99" :background "#2e2f30" ))))
   '(cursor ((t (:background "#cccccb" ))))
   '(fringe ((t (:background "#404244" ))))
   '(mode-line ((t (:foreground "#d0d0d0" :background "#404142" ))))
   '(region ((t (:background "#1d545c" ))))
   '(secondary-selection ((t (:background "#1d545c" ))))
   '(font-lock-preprocessor-face ((t (:foreground "#ff6aad" ))))
   '(font-lock-builtin-face ((t (:foreground "#d69aa7" ))))
   '(font-lock-comment-face ((t (:foreground "#66a334" ))))
   '(font-lock-function-name-face ((t (:foreground "#d6cf9a" :weight bold ))))
   '(font-lock-keyword-face ((t (:foreground "#45c6d6" ))))
   '(font-lock-string-face ((t (:foreground "#d69545" ))))
   '(font-lock-type-face ((t (:foreground "#ff8080" ))))
   '(font-lock-constant-face ((t (:foreground "#ff8080" ))))
   '(font-lock-variable-name-face ((t (:foreground "#d6bb9a" ))))
   '(minibuffer-prompt ((t (:foreground "#d5ba99" :bold t ))))
   '(font-lock-warning-face ((t (:foreground "red" :bold t ))))
   )
